### ISSUE TITLE
Issue in the /d switch

### ISSUE THREAD

**Issue by agamsol** [ixe013/notifu#3]
the /d switch is not setting the seconds to be the correct amount

**Comment by ixe013** [comment]
Sorry for the inconvenience @agamsol . 

Windows has the last word on the life of the popup, not Notifu. In recent version of Windows (starting with Windows 7 iirc), Windows will dismiss the popup after about 5 seconds unless your mouse cursor is right abouve the popup.

Try with this command line:

```
notifu /m "Delay test" /d 35
```

The popup will dismiss after 5 seconds. Call it again, but this time put your mouse over the popup (without clicking). You will get the full 35 seconds.

**Comment by agamsol** [comment]
Im a fan of this program, so you say it cannot be fixed? Because the time is most important feature so it wont go away

**Comment by ixe013** [comment]
It can`t be fixed... because Microsoft does not not see this as a problem : they don't want programe annoying users with countless popups, so it controls what can be done. From Windows point of view, the program you use to display a popup does not matter. After 5 seconds, you've had your time. Your only chance is if the user moves the mouse over it.

I honestly agree with that. No popup is so important that it deserves to stay on screen forever.
